- hosts: all
  become: yes
  tasks:

    - name: Run apt update
      apt:
        update_cache: yes
      when: pkg == "update"

    - name: Run apt upgrade
      apt:
        upgrade: yes
      when: pkg == "upgrade"

    - name: Install package "{{ pkg }}"
      apt:
        name: "{{ pkg }}"
        state: present
        update_cache: yes
      when: pkg != "update" and pkg != "upgrade"
